ua-snap/hsiaa

- package.json
- public/index.html
- src/App.vue
- src/components/Footer.vue
- src/main.js
Test this with two different simulated horizontal resolutions -- ~315px and ~750px.  In the first case you should get no map / no ability to choose a place.  At 750, you should get no map but ability to pick a community.
Known issue: you can only pick a community once 😄 because then the community selector is hidden.  Not sure why, but making the selector visible when viewing the report causes some problem which breaks the app 😦 so we're not doing that right now and can fix it as its own issue.
> Mobile improve

- src/App.vue
- src/components/Footer.vue
To check this...
- Ensure there's a credit blurb for Rasdaman in the footer, check that it links to the Zenodo DOI for Rasdaman
- Compared to the original tool, the links should now be a bit higher-contrast.  Links in the footer should be underlined.
- Switch to Mobile view.  The UAF logo in the footer should be centered.
- In Desktop view, the UAF logo should be a bit smaller than before, and properly vertically-aligned with the rest of the footer.
> add Rasdaman credits + fixup styles

- src/App.vue
Removes nlfresco@alaska.edu from the site and is replaced with our joint email group uaf-snap-data-tools@alaska.edu.
Fixes #33
> Updates email to our uaf-snap-data-tools@alaska.edu address

- src/App.vue
This PR disables the past month and next month button when appropriate to indicate a user has reached the minimum or maximum date available in the Sea Ice Atlas.
Closes #30
> Disables past month or next month button to indicate when on min / max dates.

- .env
- .env.development
Closes #41 
This PR updates the development and production environment to point at maps.earthmaps.io for the WMS endpoint for the Rasdaman sea ice coverage.
> Updates HSIAA to point at maps.earthmaps.io Varnish cache for the sea ice Rasdaman coverage.

- public/index.html
**Note: This change was already merged into the `vue3-hero` branch via PR #47, but it's looking like we'll be upgrading the Umami server to v2 before the `vue3-hero` branch is ready for prime time, so it's important that we update the Umami script URL to the v2 version in the `main` branch in the interim. That's what this PR does.**
This PR updates the Umami script URL to work with Umami v2. I.e., `umami.js` was changed to `script.js`.
You will need the Umami v2 Vagrant VM to test against. If you do not already have this set up, refer to the Vagrant instructions in https://github.com/ua-snap/nccwsc-projects/pull/154.
With the Vagrant VM running, and assuming Umami's port is forwarded to port 9999 of the host, simply change the Umami config in `public/index.html` to:
```
<script
async …
```
> Update Umami script URL to v2 version

- src/components/ConcentrationPlot.vue
- src/components/Tapestry.vue
- src/stores/atlas.js
This PR restores the "Loading data..." message when waiting to receive data for a location, and also fixes a bug that was preventing the charts from loading on initial report page load.
To test, pick a location on the map and make sure you see the "Loading data..." message in two different places on the page (the concentration plot and the tapestry plot) while the data is being fetched. The message should go away once the two types of plots load. Go back, pick another place, and make sure the "Loading data..." message continues to work as expected.
> Show "Loading data..." text when data is loading

- src/App.vue
This PR fixes the "Download a poster" PDF link on the front page of the app by simply moving the poster PDF into the `public` subdirectory and linking to it using a relative link.
To test, load the app and confirm that the "Download a poster" link links to the PDF!
> Fix the link to poster PDF

- vite.config.js
This PR sets the URL base path in `vite.config.js` to match the `publicPath` set in `vue.config.ts`, adapting to the `NODE_ENV` environment variable in the same way. Without this change, the built & deployed webapp will not load when served from the /tools/sea-ice-atlas subpath.
If you're curious what happens without this change, run the following:
```
git checkout vue3-hero
npm run build
mkdir tools
mv dist tools/sea-ice-atlas
python -m http.server
```
Then visit the webapp at http://localhost:8000/tools/sea-ice-atlas and observe that you get a blank white page with loading errors in the web console.
To verify that this change fixes this problem, run the following:
```
rm -fr tools
git checkout production_path_fix
npm run build
mkdir tools
mv dist tools/sea-ice-atlas
python -m …
```
> Set base URL in Vite config to fix production subpath load issue

- src/components/ConcentrationPlot.vue
Closes #70.
This PR changes one line of code that was preventing charts from loading properly for some communities (or probably just intermittently depending on how long it took the API to return sea ice data for the location). Instead of checking if `apiData` (a Vue 3 reference object) exist, it now checks whether `apiData.value` exists to make sure the data from the API is available before attempting to populate the line and canvas charts.
To replicate this, go to our production Historical Sea Ice Atlas app here:
https://snap.uaf.edu/tools/sea-ice-atlas/
Try selecting Utqiagvik from the community dropdown menu. If the charts fail to load properly, look at your browser's console output and you'll see that it's bombing out on a `split` operation that can be traced back to this chunk of …
> Check for presence of apiData.value before population charts

- src/components/ConcentrationPlot.vue
This PR fixes the logic for identifying the correct month so that it no longer does the modulo of 12 but 13 to catch all 12 months as expected.
To test, choose any point on the Sea Ice map on the production site, and see that when you ask for December in the concentration plot, it doesn't display anything. On this current branch, if you do the same, it will return data.
> Required change to allow for December to show up in concentration plot.

- package-lock.json
- package.json
- src/components/Map.vue
This PR ensures that the circular hsia_mask layer is always displayed above the hsia_arctic_production and base OSM layer. To achieve this, a new Leaflet pane with a higher z-index was created and assigned to the mask layer. The mask layer is now consistently rendered on top, improving the visual clarity of the data overlay.
> Adds circular mask to frame the data layers

- src/assets/main.css
- src/components/Tapestry.vue
This PR updates the tapestry component to use a Plotly heatmap for more consistent and clear data visualization. It also introduces handling for missing data, such as the absent July-December 2024 values, so that no hover tooltips appear over those empty regions. This ensures a cleaner and more intuitive experience when interacting with the chart.
Closes #75
> Updates tapestry to use Plotly heatmap

- index.html
- src/components/Report.vue
- src/router/index.js
- src/views/ReportView.vue
Closes #80 
This PR adds re-hydration of the HSIA app based on the report URL. To accomplish this, we needed to use the WebHashHistory functionality of the vue-router software to allow for client-side generation of these reports. This still allows for hitting back and forth in a browser window to go between reports / home page of the application.
Try a few locations and ensure that if you reload the page you are seeing the report displaying properly.
> Re-hydration of the app based on report URL

- src/components/Map.vue
Closes #83 
Look at the zoom controls: no longer underlined and better centered
> Remove underline from map controls, and slightly fix position

- src/communities.js
- src/components/Map.vue
- src/components/Report.vue
- src/stores/atlas.js
This PR adds a step to clear the report data after the Map component has been mounted. This prevents the possibility of going into a community, clicking either the back button on the browser, or the back button in the application and then clicking on a point on the map and still seeing the name of the community shown.
Additionally, this PR fixes the lat / lon of the Toksook, Alaska community to the nearest available pixel with data. 
Closes #74
> Clear store data on map entry & fixes Toksook lat / lon 

- src/assets/main.css
- src/components/BackButton.vue
- src/components/CommunityPicker.vue
- src/components/InvalidPlace.vue
- src/components/LoadingBlock.vue
- src/components/Map.vue
- src/components/Report.vue
- src/router/index.js
- src/views/MapView.vue
- src/views/ReportView.vue
Closes #103 
Closes #102 
Testing: run the app as normal.
- Pick a community.  The app should switch to the Report view, with the viewport centered so the "Back to the map" button is at the top.
- Click "Back to the map."  You should see the "To get started..." within the viewport (it may smooth-scroll there)
- Click somewhere way down south where there is no sea ice
- You should get the report properly framed in the viewport, with an improved "There is nothing here" message (language and formatting).  No chart/tapestry should be visible now.
Changes to look out for:
- There's now a #hash in the URL to ensure proper scroll position behavior.  Do we hate that?
- I removed a duplicate "Loading..." component, just kept the one at the top
- I fixed show/hide behavior for a number of …
> Improve error handling, target location on page with scroll behavior

- src/App.vue
- src/components/ConcentrationPlot.vue
- src/components/Header.vue
- src/components/Intro.vue
- src/components/MonthSelectors.vue
- src/components/ReportTitle.vue
- src/components/Tapestry.vue
- src/components/YearSlider.vue
- src/shared.js
- src/stores/atlas.js
This PR uses a new endpoint on the API that allows for this code to dynamically update its maximum year and month based on the data available within our data server. Currently, that maximum is year = 2024 and month = 6, but the next time we update the sea ice data, it will automatically recognize that there is new data to be displayed and adjust the year slider, month selector, and xrange for the charts accordingly. 
To test:
Have this version of the API running locally: https://github.com/ua-snap/data-api/pull/508
export VITE_SNAP_API_URL=http://localhost:5000
export VITE_WMS_URL=https://zeus.snap.uaf.edu/rasdaman/ows
npm run dev
Notice that the year slider has a maximum of 2024 and you can't go past the month of June. The charts should also all display properly given the correct range …
> Uses the API to determine the maximum year and month that we have data for

- src/App.vue
This PR updates the HREF for the poster to be from the root level of the site when in a report rather than trying to replace just the top level of the URL.
STR:
* Go to http://dev.seaiceatlas.org
* Click on a location on the map
* Click on the link "Download a poster" towards the bottom of the page
Expected: Opens the PDF of the poster
Actual: It screws up the URL and nothing is shown.
This PR pushes the URL to go from the root level and will fix this issue.
> Updates link for poster link to work when in a report.

- index.html
Closes #113.
This PR simply updates the domain enforcement in the webapp's Umami configuration to use the new seaiceatlas.org domain. I've also updated the the Historical Sea Ice Atlas website settings on the Umami server to recognize this domain.
> Update domain to seaiceatlas.org in Umami configuration

- src/components/Report.vue
- src/stores/atlas.js
Closes #115.
This PR fixes the CSV download link by constructing and loading it from the store.
To test, run the app like this:
```
export VITE_WMS_URL=https://zeus.snap.uaf.edu/rasdaman/ows
npm run dev
```
Then click a location to load its report page, then click the CSV download link.
> Fix CSV download link
